services:
  antsy:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/bash", "/entrypoint.sh"]

    # working_dir: /home/user/antsy
    volumes:
      - ./:/home/antsy
      - /dev:/dev
      - /tmp:/tmp
      - /var/log/journal:/var/log/journal
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/user/.Xauthority:ro
    environment:
      # Application
      - DATA_PATH=${PWD}/data
      # Graphics
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      # ROS 2
      - COLCON_HOME=${PWD}/.colcon
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # Other
      - HISTFILE=${PWD}/.bash_history
    devices:
      - /dev/dri:/dev/dri  # Allow access to GPU devices if needed
      - /dev/uinput
    #runtime: nvidia
    # network_mode: ${NETWORK_MODE:-host}
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ulimits:
      core: 0
    # shm_size: 256m
    shm_size: 512M

  remote_control:
    build:
      context: .
      dockerfile: Dockerfile
    command: 
      [
        "/bin/bash",
        "-c",
        "
        echo 'Connecting to gamepad...';
        ds4drv --led 00ff00;
        "
      ]
    working_dir: ${PWD}
    volumes:
      - ./:${PWD}
      - /dev:/dev
      - /tmp:/tmp
      - /var/log/journal:/var/log/journal
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/user/.Xauthority:ro
    environment:
      # Application
      - DATA_PATH=${PWD}/data
      # Graphics
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      # ROS 2
      - COLCON_HOME=${PWD}/.colcon
      - ROS_DOMAIN_ID=0
      # Other
      - HISTFILE=${PWD}/.bash_history
    devices:
      - /dev/dri:/dev/dri  # Allow access to GPU devices if needed
      - /dev/uinput
    #runtime: nvidia
    network_mode: "host"
    # network_mode: ${NETWORK_MODE:-host}
    privileged: true
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ulimits:
      core: 0
    # shm_size: 256m
    shm_size: 512M

  simulator:
    build:
      context: ./simulator
    container_name: antsy-gazebo
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    #runtime: nvidia
    environment:
    # Application
      - DATA_PATH=/home/antsy/data
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # ROS 2
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./:/home/antsy
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # Ensure the launch file exists and is executable
    command: ["/bin/bash", "/ros_entrypoint.sh"]
